spring:
  profiles:
    default: local
  datasource:
    url: jdbc:h2:mem:h2db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create

---
spring:
  config:
    activate:
      on-profile: local


  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

file:
  dir: C:\Users\user\IdeaProjects\multiplexShopPR\src\main\resources\static\img\


---
spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

file:
  dir: C:\Users\user\IdeaProjects\multiplexShopPR\src\main\resources\static\img\