spring:
  profiles:
    default: local
  datasource:
    url: jdbc:mysql://localhost:3306/sys
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Sys123!@
  jpa:
    hibernate:
      ddl-auto: none

---
spring:
  thymeleaf:
    cache: false
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create
    defer-datasource-initialization: true
    thymeleaf:
      cache: false
  logging:
    level:
      org.springframework: DEBUG
      org.hibernate: DEBUG


file:
  dir: /home/ec2-user/picture/

webpath: file:/home/ec2-user/picture/




---
spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never
